src/SistemasWeb/AlbumBundle/Controller/UserController.php
<?php

namespace SistemasWeb\AlbumBundle\Controller;

use SistemasWeb\AlbumBundle\Entity\Album;
use SistemasWeb\AlbumBundle\Entity\Photo;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class UserController extends Controller
{
    public function logoutAction() {
        $session = $this->getRequest()->getSession();
        $session->clear();
        return $this->redirect($this->generateUrl('album_homepage'));
    }
    public function dashboardAction() {
        if(!$this->isLogged()) {
            return $this->redirect($this->generateUrl('album_homepage'));
        }
        $session = $this->getRequest()->getSession();
        $user = $session->get('login');
        return $this->render('AlbumBundle:User:index.html.twig', array('user'=> $user));
    }
    public function createAlbumAction(Request $request) {
        if(!$this->isLogged()) {
            return $this->redirect($this->generateUrl('album_homepage'));
        }
        $session = $this->getRequest()->getSession();
        $user = $session->get('login');
        $em = $this->getDoctrine()->getEntityManager();
        $repository = $em->getRepository("AlbumBundle:Album");
        if($this->get('request')->getMethod() == 'POST') {
            $nombre = $request->request->get('nombre');
            $privacidad = $request->request->get('privacidad');
            $existe = $repository->findOneBy(array('nombre' => $nombre));
            if($existe) {
                $albums = $repository->findBy(array('userId' => $user->getId()));
                return $this->render('AlbumBundle:User:create.html.twig', array('user'=> $user, 'albums' => $albums, 'message' => 'Ya existe un album con ese nombre'));
            }
            $album = new Album();
            $album->setNombre($nombre);
            $album->setUserId($user->getId());
            $album->setPrivate(0);
            $album->setPublic(0);
            switch($privacidad) {
                case 'private':
                    $album->setPrivate(1);
                    break;
                case 'public':
                    $album->setPublic(1);
                    break;
            }
            $em->persist($album);
            $em->flush();
        }
        $albums = $repository->findBy(array('userId' => $user->getId()));
        return $this->render('AlbumBundle:User:create.html.twig', array('user'=> $user, 'albums' => $albums));
    }

    public function uploadPhotoAction(Request $request, $id) {
        if(!$this->isLogged()) {
            return $this->redirect($this->generateUrl('album_homepage'));
        }
        $session = $this->getRequest()->getSession();
        $user = $session->get('login');
        $em = $this->getDoctrine()->getEntityManager();
        $repository = $em->getRepository("AlbumBundle:Album");
        $repositoryPhotos = $em->getRepository("AlbumBundle:Photo");
        $album = $repository->findOneBy(array('id' => $id));
        $photos = $repositoryPhotos->findBy(array('albumId' => $id));
        return $this->render('AlbumBundle:User:add.html.twig', array('user'=> $user, 'album' => $album , 'photos' => $photos));
    }
    public function uploadAction(Request $request) {
        if(!$this->isLogged()) {
            return new Response("Not logged");
        }
        $session = $this->getRequest()->getSession();
        $user = $session->get('login');
        $em = $this->getDoctrine()->getEntityManager();
        $repositoryPhotos = $em->getRepository("AlbumBundle:Photo");
        if($this->get('request')->getMethod() == 'POST') {
            $nombre = $request->request->get('nombre');
            $album = $request->request->get('album');
            $image = $_FILES['image'];
            $tmp_file = $image['tmp_name'];

            $stream_file = fopen($tmp_file, 'rb');
            $photo = new Photo();
            $photo->setNombre($nombre);
            $photo->setAlbumId($album);
            $photo->setUserId($user->getId());
            $photo->setImage(stream_get_contents($stream_file));

            $em->persist($photo);
            $em->flush();
        }
        return new Response("Uploaded");
    }

    public function editAction(Request $request) {
        if(!$this->isLogged()) {
            return $this->redirect($this->generateUrl('album_homepage'));
        }
        $session = $this->getRequest()->getSession();
        $user = $session->get('login');
        $em = $this->getDoctrine()->getEntityManager();
        $repository = $em->getRepository("AlbumBundle:User");
        if($this->get('request')->getMethod() == 'POST') {
            $oldpassword = $request->request->get('oldpassword');
            $newpassword = $request->request->get('newpassword');
            $usuarioExistente = $repository->findOneBy(array('username' => $user->getUsername(), 'password' => sha1($oldpassword)));
            if ($usuarioExistente) {
                $usuarioExistente->setPassword(sha1($newpassword));
                $em->persist($usuarioExistente);
                $em->flush();
                $session->clear();
                return $this->render('AlbumBundle:User:edit.html.twig', array('user' => $user, 'success' => 'Modificado password'));
            } else {
                return $this->render('AlbumBundle:User:edit.html.twig', array('user' => $user, 'message' => 'Contraseña incorrecta'));
            }
        }
        return $this->render('AlbumBundle:User:edit.html.twig', array('user'=> $user));
    }

    public function showImageAction($id) {
        $session = $this->getRequest()->getSession();
        $user = $session->get('login');
        $em = $this->getDoctrine()->getEntityManager();
        $repository = $em->getRepository("AlbumBundle:Photo");
        $repositoryAlbums = $em->getRepository("AlbumBundle:Album");
        $photo = $repository->findOneBy(array('id' => $id));
        $album = $repositoryAlbums->findOneBy(array('id' => $photo->getAlbumId()));
        if($album->getPrivate() == 1) {
            if(!($album->getUserId() == $user->getId())) {
                return $this->render('AlbumBundle:Default:error.html.twig', array('message' => 'Esta foto es privada', 'user' => $user));
            }
        }
        return $this->render('AlbumBundle:User:photo.html.twig', array('user' => $user,'photo' => $photo));
    }

    private function isLogged() {
        $session = $this->getRequest()->getSession();
        $user = $session->get('login');
        if($user) {
            return true;
        }
        return false;
    }
    private function isAdmin() {
        $session = $this->getRequest()->getSession();
        $user = $session->get('login');

        if ($user->getAdmin()) {
            return true;
        } else {
            return false;
        }
    }
}
?>

src/SistemasWeb/AlbumBundle/Resources/views/Admin/album.html.twig
{% extends "::base.html.twig" %}

{% block header %}
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button> <a class="navbar-brand" href="{{ path('album_homepage') }}"><img src="{{ asset('bundles/album/images/camera.png') }}" />PhotoAlbum Online</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <!--
            <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input class="form-control" type="text">
                </div>
                <button type="submit" class="btn btn-default">
                    Submit
                </button>
            </form>
            -->
            <ul class="nav navbar-nav navbar-right">
                {% if user.admin %}
                    <li>
                        <a href="{{ path('admin_homepage') }}">Administración</a>
                    </li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.username }}<strong class="caret"></strong></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{{ path('album_create') }}">Crear Album</a>
                        </li>
                        <li>
                            <a href="{{ path('user_edit') }}">Cambiar contraseña</a>
                        </li>
                        <li class="divider">
                        </li>
                        <li>
                            <a href="{{ path('user_logout') }}">Logout</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
{% endblock %}

{% block body %}
    <div class="row">
        <center>
            <table>
                <tr>
                    <th>Id</th>
                    <th>UserID</th>
                    <th>Nombre</th>
                    <th>Opciones</th>
                </tr>
                <tr>
                    {% for album in albums %}
                    <td width="100px" height="30px">{{ album.id }}</td>
                    <td width="100px">{{ album.userId }}</td>
                    <td width="200px">{{ album.nombre }}</td>
                    <td width="200px">
                        <a href="{{ path('admin_removeAlbum', {'id': album.id}) }}">Eliminar Album</a>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </center>
    </div>
{% endblock %}

src/SistemasWeb/AlbumBundle/Resources/views/Admin/index.html.twig
{% extends "::base.html.twig" %}

{% block header %}
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button> <a class="navbar-brand" href="{{ path('album_homepage') }}"><img src="{{ asset('bundles/album/images/camera.png') }}" />PhotoAlbum Online</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <!--
            <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input class="form-control" type="text">
                </div>
                <button type="submit" class="btn btn-default">
                    Submit
                </button>
            </form>
            -->
            <ul class="nav navbar-nav navbar-right">
                {% if user.admin %}
                    <li>
                        <a href="{{ path('admin_homepage') }}">Administración</a>
                    </li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.username }}<strong class="caret"></strong></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{{ path('album_create') }}">Crear Album</a>
                        </li>
                        <li>
                            <a href="{{ path('user_edit') }}">Cambiar contraseña</a>
                        </li>
                        <li class="divider">
                        </li>
                        <li>
                            <a href="{{ path('user_logout') }}">Logout</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
{% endblock %}

{% block body %}
    <div class="row">
        <center><a class="admin" href="{{ path('admin_album') }}">Administrar Albumes</a>
            <a class="admin" href="{{ path('admin_user') }}">Administrar Usuarios</a>
            <a class="admin" href="{{ path('admin_photos') }}">Administrar Fotos</a></center>
    </div>
{% endblock %}

src/SistemasWeb/AlbumBundle/Resources/views/Admin/photo.html.twig
{% extends "::base.html.twig" %}

{% block header %}
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button> <a class="navbar-brand" href="{{ path('album_homepage') }}"><img src="{{ asset('bundles/album/images/camera.png') }}" />PhotoAlbum Online</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <!--
            <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input class="form-control" type="text">
                </div>
                <button type="submit" class="btn btn-default">
                    Submit
                </button>
            </form>
            -->
            <ul class="nav navbar-nav navbar-right">
                {% if user.admin %}
                    <li>
                        <a href="{{ path('admin_homepage') }}">Administración</a>
                    </li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.username }}<strong class="caret"></strong></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{{ path('album_create') }}">Crear Album</a>
                        </li>
                        <li>
                            <a href="{{ path('user_edit') }}">Cambiar contraseña</a>
                        </li>
                        <li class="divider">
                        </li>
                        <li>
                            <a href="{{ path('user_logout') }}">Logout</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
{% endblock %}

{% block body %}
    <div class="row">
        <center>
        <table>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>AlbumId</th>
                <th>Opciones</th>
            </tr>
            <tr>
                {% for photo in photos %}
                <td width="100px" height="30px">{{ photo.id }}</td>
                <td width="100px">{{ photo.nombre }}</td>
                <td width="200px">{{ photo.albumId }}</td>
                <td width="200px">
                    <br />
                    <a href="{{ path('admin_removePhoto', {'id': photo.id}) }}">Eliminar Foto</a>
                </td>
            </tr>
            {% endfor %}
        </table>
        </center>
    </div>
{% endblock %}

src/SistemasWeb/AlbumBundle/Resources/views/Admin/user.html.twig
{% extends "::base.html.twig" %}

{% block header %}
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button> <a class="navbar-brand" href="{{ path('album_homepage') }}"><img src="{{ asset('bundles/album/images/camera.png') }}" />PhotoAlbum Online</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <!--
            <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input class="form-control" type="text">
                </div>
                <button type="submit" class="btn btn-default">
                    Submit
                </button>
            </form>
            -->
            <ul class="nav navbar-nav navbar-right">
                {% if user.admin %}
                    <li>
                        <a href="{{ path('admin_homepage') }}">Administración</a>
                    </li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.username }}<strong class="caret"></strong></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{{ path('album_create') }}">Crear Album</a>
                        </li>
                        <li>
                            <a href="{{ path('user_edit') }}">Cambiar contraseña</a>
                        </li>
                        <li class="divider">
                        </li>
                        <li>
                            <a href="{{ path('user_logout') }}">Logout</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
{% endblock %}

{% block body %}
    <div class="row">
        <center>
        <table>
            <tr>
                <th>Id</th>
                <th>User</th>
                <th>Correo</th>
                <th>Opciones</th>
            </tr>
            <tr>
                {% for user in users %}
                <td width="100px" height="30px">{{ user.id }}</td>
                <td width="100px">{{ user.username }}</td>
                <td width="200px">{{ user.email }}</td>
                <td width="200px">
                    {% if user.active == true %}

                        <a href="{{ path('admin_deactivate', {'id': user.id}) }}">Desactivar Usuario</a>

                    {% else %}
                        <a href="{{ path('admin_activate', {'id': user.id}) }}">Activar Usuario</a>
                    {% endif %}
                    <br />
                    <a href="{{ path('admin_removeUser', {'id': user.id}) }}">Eliminar Usuario</a>
                </td>
            </tr>
            {% endfor %}
        </table>
        </center>
    </div>
{% endblock %}